// NOTE: Any change here must be reflected in preload.cts file.
export const IpcCommands = {
    INCREASE_ONCE: "INCREASE_ONCE",
    DECREASE_ONCE: "DECREASE_ONCE",
    INCREASE_START: "INCREASE_START",
    INCREASE_STOP: "INCREASE_STOP",
    DECREASE_START: "DECREASE_START",
    DECREASE_STOP: "DECREASE_STOP",
    MOVE_TO_CENTER: "MOVE_TO_CENTER",
    ON_ARDUINO_ANGLE_CHANGED: "ON_ARDUINO_ANGLE_CHANGED",
    CONNECT: "CONNECT",
    DISCONNECT: "DISCONNECT",
    ON_DISCONNECTED: "ON_DISCONNECTED",
    SET_ANGLE_OF_SERVO_CENTER_TO_NORTH: "SET_ANGLE_OF_SERVO_CENTER_TO_NORTH",
    SET_IP_AND_PORT: "SET_IP_AND_PORT",
    SET_STEP: "SET_STEP",
    GET_SAVED_STATE: "GET_SAVED_STATE",
    ON_ERROR: "ON_ERROR"
};