// NOTE: Any change here must be reflected in preload.cts file.
export const IpcCommands = {
    INCREASE_ONCE: "INCREASE_ONCE",
    DECREASE_ONCE: "DECREASE_ONCE",
    INCREASE_START: "INCREASE_START",
    INCREASE_STOP: "INCREASE_STOP",
    DECREASE_START: "DECREASE_START",
    DECREASE_STOP: "DECREASE_STOP",
    MOVE_TO_CENTER: "MOVE_TO_CENTER",
    ON_ARDUINO_ANGLE_CHANGED: "ON_ARDUINO_ANGLE_CHANGED",
    GET_PORTS: "GET_PORTS",
    CONNECT_TO_PORT: "CONNECT_TO_PORT",
    ON_PORT_DISCONNECTED: "ON_PORT_DISCONNECTED",
    GET_ANGLE_OF_SERVO_CENTER_TO_NORTH: "GET_ANGLE_OF_SERVO_CENTER_TO_NORTH",
    SET_ANGLE_OF_SERVO_CENTER_TO_NORTH: "SET_ANGLE_OF_SERVO_CENTER_TO_NORTH"
};